name: release

permissions:
  contents: write

on: [push, pull_request, workflow_dispatch]

env: 
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  APPLICATION_NAME: rife-ncnn-vulkan-ex

jobs: 

  setup:
    runs-on: ubuntu-latest
    outputs:
      APPNAME: ${{ steps.get_appname.outputs.APPNAME }}
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
    - name: get-appname
      id: get_appname
      run: echo "APPNAME=${APPLICATION_NAME}" >> $GITHUB_OUTPUT
    - name: get-version
      id: get_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

  ubuntu:
    needs: [setup]
    runs-on: ubuntu-22.04
    env:
      PACKAGENAME: ${{ needs.setup.outputs.APPNAME }}-${{ needs.setup.outputs.VERSION }}-ubuntu
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: vulkansdk
      run: |
        wget https://sdk.lunarg.com/sdk/download/1.4.335.0/linux/vulkansdk-linux-x86_64-1.4.335.0.tar.xz -O vulkansdk-linux-x86_64-1.4.335.0.tar.gz
        tar -xf vulkansdk-linux-x86_64-1.4.335.0.tar.gz
        rm -rf 1.4.335.0/source 1.4.335.0/samples
        find 1.4.335.0 -type f | grep -v -E 'vulkan|glslang' | xargs rm
    - name: build
      run: |
        sudo apt install cmake gcc g++ --yes
        ls
        mkdir build
        export VULKAN_SDK=`pwd`/1.4.335.0/x86_64 && cd build && cmake ../src && cmake --build . -j 2
    - name: package
      run: |
        mkdir -p ubuntu
        cp README.md LICENSE ubuntu
        cp build/${{ needs.setup.outputs.APPNAME }} ubuntu
        strip -g ubuntu/${{ needs.setup.outputs.APPNAME }}
        cp -r models/* ubuntu
        zip -9 -r ubuntu.zip ubuntu
    - name: log
      run: |
          ls
          cd build && ls
          
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu
        path: ubuntu.zip

  ubuntu-arm:
    needs: [setup]
    runs-on: ubuntu-22.04-arm
    env:
      PACKAGENAME: ${{ needs.setup.outputs.APPNAME }}-${{ needs.setup.outputs.VERSION }}-ubuntu-arm
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: deps
      run: |
        sudo apt install mesa-vulkan-drivers vulkan-tools cmake gcc g++ libvulkan-dev --yes
    - name: build
      run: |
        mkdir build
        cd build && cmake ../src && cmake --build . -j 2
    - name: package
      run: |
        mkdir -p ubuntu-arm
        cp README.md LICENSE ubuntu-arm
        cp build/${{ needs.setup.outputs.APPNAME }} ubuntu-arm
        strip -g ubuntu-arm/${{ needs.setup.outputs.APPNAME }}
        cp -r models/* ubuntu-arm
        zip -9 -r ubuntu-arm.zip ubuntu-arm
    - name: log
      run: |
          ls
          cd build && ls
          
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-arm
        path: ubuntu-arm.zip
    

  openmp-macos:
    runs-on: macos-latest
    steps:
    - name: cache-openmp
      id: cache-openmp
      uses: actions/cache@v4
      with:
        path: openmp-install
        key: openmp-macos-release-11.0.0
    - name: Select Xcode version
      run: sudo xcode-select --switch '/Library/Developer/CommandLineTools'
    
    - name: checkout
      if: steps.cache-openmp.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
    - name: openmp
      if: steps.cache-openmp.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/openmp-11.0.0.src.tar.xz
        tar -xf openmp-11.0.0.src.tar.xz
        cd openmp-11.0.0.src
        sed -i'' -e '/.size __kmp_unnamed_critical_addr/d' runtime/src/z_Linux_asm.S
        sed -i'' -e 's/__kmp_unnamed_critical_addr/___kmp_unnamed_critical_addr/g' runtime/src/z_Linux_asm.S
    - name: build-x86_64
      if: steps.cache-openmp.outputs.cache-hit != 'true'
      run: |
        cd openmp-11.0.0.src
        mkdir build-x86_64 && cd build-x86_64
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DCMAKE_OSX_ARCHITECTURES="x86_64" \
            -DLIBOMP_ENABLE_SHARED=OFF -DLIBOMP_OMPT_SUPPORT=OFF -DLIBOMP_USE_HWLOC=OFF -DCMAKE_POLICY_VERSION_MINIMUM=3.5 ..
        cmake --build . -j 3
        cmake --build . --target install
    - name: build-arm64
      if: steps.cache-openmp.outputs.cache-hit != 'true'
      run: |
        cd openmp-11.0.0.src
        mkdir build-arm64 && cd build-arm64
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DCMAKE_OSX_ARCHITECTURES="arm64" \
            -DLIBOMP_ENABLE_SHARED=OFF -DLIBOMP_OMPT_SUPPORT=OFF -DLIBOMP_USE_HWLOC=OFF -DCMAKE_POLICY_VERSION_MINIMUM=3.5 ..
        cmake --build . -j 3
        cmake --build . --target install
    - name: merge-fat-library
      if: steps.cache-openmp.outputs.cache-hit != 'true'
      run: |
        rm -rf $GITHUB_WORKSPACE/openmp-install
        mkdir -p $GITHUB_WORKSPACE/openmp-install
        cp -r openmp-11.0.0.src/build-x86_64/install/include $GITHUB_WORKSPACE/openmp-install
        mkdir -p $GITHUB_WORKSPACE/openmp-install/lib
        lipo -create openmp-11.0.0.src/build-x86_64/install/lib/libomp.a openmp-11.0.0.src/build-arm64/install/lib/libomp.a -o $GITHUB_WORKSPACE/openmp-install/lib/libomp.a
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: openmp-macos
        path: openmp-install

  macos:
    needs: [setup, openmp-macos]
    runs-on: macos-latest
    env:
      PACKAGENAME: ${{ needs.setup.outputs.APPNAME }}-${{ needs.setup.outputs.VERSION }}-macos
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: download-openmp-macos
      uses: actions/download-artifact@v4
      with:
        name: openmp-macos
        path: openmp-macos
    - name: install-openmp
      run: |
        sudo cp openmp-macos/include/* $DEVELOPER_DIR/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
        sudo cp openmp-macos/lib/libomp.a $DEVELOPER_DIR/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v4
      with:
        path: "vulkansdk-macos-1.4.335.0"
        key: vulkansdk-macos-1.4.335.0
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: |
        wget https://sdk.lunarg.com/sdk/download/1.4.335.0/mac/vulkansdk-macos-1.4.335.0.zip -O vulkansdk-macos-1.4.335.0.zip
        unzip vulkansdk-macos-1.4.335.0.zip
        chmod +x `pwd`/vulkansdk-macOS-1.4.335.0.app/Contents/MacOS/vulkansdk-macOS-1.4.335.0
        SDKDIR=`pwd`/VulkanSDK
        `pwd`/vulkansdk-macOS-1.4.335.0.app/Contents/MacOS/vulkansdk-macOS-1.4.335.0 \
        --root $SDKDIR \
        --accept-licenses \
        --default-answer \
        --confirm-command install \
        copy_only=1
    - name: build-x86_64
      run: |
        VulkanDIR=`pwd`/VulkanSDK
        export VULKAN_SDK=$VulkanDIR
        SDKDIR=$VulkanDIR/macOS
        INCLUDE_DIR=$SDKDIR/include
        LIB_DIR=$SDKDIR/lib/MoltenVK.xcframework/macos-arm64_x86_64
        mkdir build-x86_64 && cd build-x86_64
        cmake -DUSE_STATIC_MOLTENVK=ON -DCMAKE_OSX_ARCHITECTURES="x86_64" \
            -DOpenMP_C_FLAGS="-Xclang -fopenmp" -DOpenMP_CXX_FLAGS="-Xclang -fopenmp" \
            -DOpenMP_C_LIB_NAMES="libomp" -DOpenMP_CXX_LIB_NAMES="libomp" \
            -DOpenMP_libomp_LIBRARY="$DEVELOPER_DIR/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libomp.a" \
            -DVulkan_SDK=$SDKDIR \
            -DVulkan_INCLUDE_DIR=$INCLUDE_DIR \
            -DVulkan_LIBRARY=$LIB_DIR/libMoltenVK.a \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
            -DCMAKE_EXE_LINKER_FLAGS="-framework Metal -framework Foundation -framework IOSurface -framework QuartzCore" \
            ../src
        cmake --build . -j 3
    - name: build-arm64
      run: |
        VulkanDIR=`pwd`/VulkanSDK
        export VULKAN_SDK=$VulkanDIR
        SDKDIR=$VulkanDIR/macOS
        INCLUDE_DIR=$SDKDIR/include
        LIB_DIR=$SDKDIR/lib/MoltenVK.xcframework/macos-arm64_x86_64
        mkdir build-arm64 && cd build-arm64
        cmake -DUSE_STATIC_MOLTENVK=ON -DCMAKE_OSX_ARCHITECTURES="arm64" \
            -DOpenMP_C_FLAGS="-Xclang -fopenmp" -DOpenMP_CXX_FLAGS="-Xclang -fopenmp" \
            -DOpenMP_C_LIB_NAMES="libomp" -DOpenMP_CXX_LIB_NAMES="libomp" \
            -DOpenMP_libomp_LIBRARY="$DEVELOPER_DIR/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libomp.a" \
            -DVulkan_SDK=$SDKDIR \
            -DVulkan_INCLUDE_DIR=$INCLUDE_DIR \
            -DVulkan_LIBRARY=$LIB_DIR/libMoltenVK.a \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
            -DCMAKE_EXE_LINKER_FLAGS="-framework Metal -framework Foundation -framework IOSurface -framework QuartzCore" \
            ../src
        cmake --build . -j 3
  #  - name: build-arm64
  #    run: |
  #      export VULKAN_SDK=`pwd`/vulkansdk-macos-1.2.189.0/macOS
  #      mkdir build-arm64 && cd build-arm64
  #      cmake -DUSE_STATIC_MOLTENVK=ON -DCMAKE_OSX_ARCHITECTURES="arm64" \
  #          -DCMAKE_CROSSCOMPILING=ON -DCMAKE_SYSTEM_PROCESSOR=arm64 \
  #          -DOpenMP_C_FLAGS="-Xclang -fopenmp" -DOpenMP_CXX_FLAGS="-Xclang -fopenmp" \
  #          -DOpenMP_C_LIB_NAMES="libomp" -DOpenMP_CXX_LIB_NAMES="libomp" \
  #          -DOpenMP_libomp_LIBRARY="$DEVELOPER_DIR/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libomp.a" \
  #          ../src
  #      cmake --build . -j 3
    - name: package
      run: |
        mkdir -p macos
        cp README.md LICENSE macos/
        lipo -create build-x86_64/${{ needs.setup.outputs.APPNAME }} build-arm64/${{ needs.setup.outputs.APPNAME }} -o macos/${{ needs.setup.outputs.APPNAME }}        
        strip macos/${{ needs.setup.outputs.APPNAME }}
        cp -r models/* macos
        zip -9 -r macos.zip macos
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: macos
        path: macos.zip

  windows:
    needs: [setup]
    runs-on: windows-latest
    env:
      PACKAGENAME: ${{ needs.setup.outputs.APPNAME }}-${{ needs.setup.outputs.VERSION }}-windows
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v4
      with:
        path: "VulkanSDK"
        key: vulkansdk-windows-X64-1.4.335.0
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.4.335.0/windows/vulkansdk-windows-X64-1.4.335.0.exe -OutFile vulkansdk-windows-X64-1.4.335.0.exe
        $InstallPath = Join-Path (Get-Location) "VulkanSDK"
        if (Test-Path $InstallPath) { Remove-Item -Recurse -Force $InstallPath }
        ./vulkansdk-windows-X64-1.4.335.0.exe --root "$InstallPath" --accept-licenses --default-answer --confirm-command install
        rm vulkansdk-windows-X64-1.4.335.0.exe
    - name: build
      run: |
        $env:VULKAN_SDK = (Join-Path (Get-Location) "VulkanSDK")
        mkdir build; cd build
        cmake -A x64 -DVULKAN_SDK="$env:VULKAN_SDK" ../src
        cmake --build . --config Release -j 2
    - name: package
      run: |
        mkdir ${{ env.PACKAGENAME }}
        Copy-Item -Verbose -Path "README.md" -Destination "${{ env.PACKAGENAME }}"
        Copy-Item -Verbose -Path "LICENSE" -Destination "${{ env.PACKAGENAME }}"
        Copy-Item -Verbose -Path "build\Release\${{ needs.setup.outputs.APPNAME }}.exe" -Destination "${{ env.PACKAGENAME }}"
        Copy-Item -Verbose -Path "C:\windows\system32\vcomp140.dll" -Destination "${{ env.PACKAGENAME }}"
        Copy-Item -Verbose -Recurse -Path "models\*" -Destination "${{ env.PACKAGENAME }}"
        7z a -r ${{ env.PACKAGENAME }}.zip ${{ env.PACKAGENAME }}

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: windows
        path: D:\a\rife-ncnn-vulkan-ex\rife-ncnn-vulkan-ex\rife-ncnn-vulkan-ex-refs\heads\ex-windows.zip

  # windows-arm:
  #   needs: [setup]
  #   runs-on: windows-latest
  #   env:
  #     PACKAGENAME: ${{ needs.setup.outputs.APPNAME }}-${{ needs.setup.outputs.VERSION }}-windows
  #   steps:
  #   - uses: actions/checkout@v4
  #     with:
  #       submodules: 'recursive'
  #   - name: cache-vulkansdk
  #     id: cache-vulkansdk
  #     uses: actions/cache@v4
  #     with:
  #       path: "VulkanSDK"
  #       key: vulkansdk-windows-X64-1.4.335.0
  #   - name: vulkansdk
  #     if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
  #     run: |
  #       Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.4.335.0/warm/vulkansdk-windows-ARM64-1.4.335.0.exe -OutFile vulkansdk-windows-ARM64-1.4.335.0.exe
  #       $InstallPath = Join-Path (Get-Location) "VulkanSDK"
  #       if (Test-Path $InstallPath) { Remove-Item -Recurse -Force $InstallPath }
  #       ./vulkansdk-windows-ARM64-1.4.335.0.exe --root "$InstallPath" --accept-licenses --default-answer --confirm-command install
  #       rm vulkansdk-windows-ARM64-1.4.335.0.exe
  #   - name: build
  #     run: |
  #       $env:VULKAN_SDK = (Join-Path (Get-Location) "VulkanSDK")
  #       mkdir build; cd build
  #       cmake -A arm64 -DVULKAN_SDK="$env:VULKAN_SDK" ../src
  #       cmake --build . --config Release -j 2
  #   - name: package
  #     run: |
  #       mkdir ${{ env.PACKAGENAME }}
  #       Copy-Item -Verbose -Path "README.md" -Destination "${{ env.PACKAGENAME }}"
  #       Copy-Item -Verbose -Path "LICENSE" -Destination "${{ env.PACKAGENAME }}"
  #       Copy-Item -Verbose -Path "build\Release\${{ needs.setup.outputs.APPNAME }}.exe" -Destination "${{ env.PACKAGENAME }}"
  #       Copy-Item -Verbose -Path "C:\windows\system32\vcomp140.dll" -Destination "${{ env.PACKAGENAME }}"
  #       Copy-Item -Verbose -Recurse -Path "models\*" -Destination "${{ env.PACKAGENAME }}"
  #       7z a -r ${{ env.PACKAGENAME }}.zip ${{ env.PACKAGENAME }}

  #   - name: upload
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: windows-arm
  #       path: D:\a\rife-ncnn-vulkan-ex\rife-ncnn-vulkan-ex\rife-ncnn-vulkan-ex-refs\heads\ex-windows.zip
  
  release:
    needs: [setup, ubuntu, windows, macos]
    runs-on: ubuntu-latest
    steps:
    - name: download
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: Generate version and tag
      id: version_tag
      run: |
          version=$(python -c "from datetime import datetime; print(str(datetime.now()).split(' ')[0].replace('-',''))")
          tag=$(python -c "import random, string; print(''.join(random.choices(string.ascii_letters, k=8)))")
          ver=$version-$tag
          echo "Version=$ver"
          echo "Tag=$tag"
          echo "version=$ver" >> $GITHUB_OUTPUT
          echo "tag=$ver" >> $GITHUB_OUTPUT
    - name: create-release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version_tag.outputs.tag }}
        release_name: Release ${{ steps.version_tag.outputs.tag }}
        draft: false
        prerelease: false
    
    - name: upload-ubuntu
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/ubuntu/ubuntu.zip
        asset_name: ubuntu.zip
        asset_content_type: application/zip

    - name: upload-macos
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PACKAGENAME: ${{ needs.setup.outputs.APPNAME }}-${{ needs.setup.outputs.VERSION }}-macos
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/macos/macos.zip
        asset_name: macos.zip
        asset_content_type: application/zip
    - name: log
      run: |
        ls
        cd artifacts
        ls
        cd windows
        ls
        
    - name: upload-windows
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PACKAGENAME: ${{ needs.setup.outputs.APPNAME }}-${{ needs.setup.outputs.VERSION }}-windows
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/windows/ex-windows.zip
        asset_name: windows.zip
        asset_content_type: application/zip